### ISSUE TITLE
Can't install on Ubuntu

### ISSUE THREAD

**Issue by ecocode** [azawawi/perl6-electron#3]
I can't install the module since tests fail. My system is Ubuntu 16.04 with node 7.4.0 from official node PPA. electron is v1.4.14.

Also, I had to add "use LWP::Simple;" in Electron::App.pm since otherwise I received error that &Simple was unkown.

<pre>
t/02-clipboard.t ......1/6App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec/.zef/store/perl6-electron.git/1d21370692c902a15a11bef703e59d9d7dd36468/resources/main_app/main.js:2:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec/.zef/store/perl6-electron.git/1d21370692c902a15a11bef703e59d9d7dd36468/resources/main_app/main.js:2:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
# Destroy electron app
Failed to connect: connection refused
  in method make_request at /home/ec/.zef/store/perl6-lwp-simple.git/01b3edfeb4027ecc51d549356449c68620845dbd/lib/LWP/Simple.pm (LWP::Simple) line 231
  in method request_shell at /home/ec/.zef/store/perl6-lwp-simple.git/01b3edfeb4027ecc51d549356449c68620845dbd/lib/LWP/Simple.pm (LWP::Simple) line 81
  in method post at /home/ec/.zef/store/perl6-lwp-simple.git/01b3edfeb4027ecc51d549356449c68620845dbd/lib/LWP/Simple.pm (LWP::Simple) line 39
  in sub  at /home/ec/.zef/store/perl6-electron.git/1d21370692c902a15a11bef703e59d9d7dd36468/lib/Electron/App.pm6 (Electron::App) line 69
  in method handler at /home/ec/.zef/store/jsonrpc.git/1fcb7aa46fe6f0077114a012add8088430160e8c/lib/JSON/RPC/Client.pm (JSON::RPC::Client) line 128
  in method <anon> at /home/ec/.zef/store/jsonrpc.git/1fcb7aa46fe6f0077114a012add8088430160e8c/lib/JSON/RPC/Client.pm (JSON::RPC::Client) line 44
  in method destroy at /home/ec/.zef/store/perl6-electron.git/1d21370692c902a15a11bef703e59d9d7dd36468/lib/Electron/App.pm6 (Electron::App) line 97
  in block <unit> at t/02-clipboard.t line 30
</pre>

**Comment by azawawi** [comment]
Fixed in #4.
